name: Kerbz Mention Tracker123 (Daily)

on:
  schedule:
    - cron: "0 13 * * *"     # 09:00 America/New_York daily sweep (13:00 UTC during EDT)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tracker
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          TIMEZONE: "America/New_York"
        run: |
          python src/main.py

      - name: Commit & push state
        run: |
          git config user.name "kerbz-mention-bot"
          git config user.email "bot@users.noreply.github.com"
          git add data/seen.json
          git diff --quiet && echo "No state changes." || (git commit -m "chore: update seen.json" && git push)
